### ISSUE TITLE
Group and Scene Limits do not work properly

### ISSUE THREAD

**Issue by GuruPG** [pharos-labs/starter-web-interface#4]
The 'gLimit - group limit' in assets/scripts/pharos.js seems to not function.
I am trying to use this in the attached (unable to attach file, email or teams for copy) with all but one group numbered above 1000.
The default of 340 does not seem to work, I also tried changing this to 1000 but still displayed groups with higher numbers.
This is being tried in Designer V 2.11.1 with Starter Web interface 8.0.2
Phil Grice

**Comment by docsteer** [comment]
I took a look at this and the way these limits work for `gLimit` and `sLimit` is not consistent. `gLimit` is a limit of the maximum *number* of groups but not the maximum group number; `sLimit` seems to be broken, but `tLimit` is working correctly. I will address this in a future update.

**Comment by docsteer** [comment]
Fixed in v8.0.3
